name: CI/CD for AutoML Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate and Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # Optional: Uncomment below to auto-apply (not recommended for prod)
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve

  lambda-zip:
    name: Zip Lambda Files
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip Lambda Scripts
      run: |
        zip start_autopilot_job.zip start_autopilot_job.py
        zip deploy_best_model.zip deploy_best_model.py

    - name: List Zipped Files
      run: ls -lah *.zip

